// THIS FILE WAS GENERATED BY A TOOL, DO NOT EDIT!

package main

import (
	"github.com/lxn/walk"
)

type dialogUI struct {
}

func (w *Dialog) init(owner walk.RootWidget) (err error) {
	if w.Dialog, err = walk.NewDialog(owner); err != nil {
		return err
	}

	succeeded := false
	defer func() {
		if !succeeded {
			w.Dispose()
		}
	}()

	var font *walk.Font
	if font == nil {
		font = nil
	}

	w.SetName("Dialog")
	if err := w.SetClientSize(walk.Size{400, 300}); err != nil {
		return err
	}
	if err := w.SetTitle(`Dialog`); err != nil {
		return err
	}

	// Tab order

	succeeded = true

	return nil
}
